version: '3.1'

services:
  joomla:
    image: joomla:5.1
    platform: linux/arm64/v8
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini

  joomladb:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    command: mysqld --innodb_use_native_aio=0
